### ISSUE TITLE
Journaling options wrong

### ISSUE THREAD

**Issue by simonrowan** [UKCloud/documentation#899]
https://docs.ukcloud.com/articles/vmware/vmw-how-zerto-create-vpg.html

This document says there is only a single service profile available. This is wrong, there are multiple profiles ranging from 2 days (I think) up to 28 days.

**Comment by suehighmoor** [comment]
Thanks for raising this. Looking into it now.

**Comment by simonrowan** [comment]
I have a ticket logged with the VMware team to enable the 28 day option, but only a 30 day option was available. VMware have gone to Guy to ask if this is OK and if pricing needs to change etc. Worth checking in with Guy to see if this has happened

**Comment by suehighmoor** [comment]
Pull request to cover this issue is here: PR #981. Just waiting for review/approval

**Comment by suehighmoor** [comment]
These changes are now published. Doc now includes information about the different service profiles available. We reverted back to calling it 28 day retention because that is what it is called in all the commercial documents. Behind the scenes it is 30 day retention, but we didn't want to introduce confusion by calling it one thing in one place and another elsewhere.
